### ISSUE TITLE
Several links in the README are dead

### ISSUE THREAD

**Issue by autonomobil** [JuliaPOMDP/POMDPExamples.jl#13]
There are several links in the README, which are dead, maybe they can be updated.

For example:

**Initial state distribution** :
 ... [initialstate(m::BabyPOMDP, rng::AbstractRNG) ](http://juliapomdp.github.io/POMDPs.jl/latest/api.html#POMDPs.initialstate)...
...[POMDPs.jl distribution interface](http://juliapomdp.github.io/POMDPs.jl/latest/interfaces.html#Distributions-1)...
...[initialstate_distribution](http://juliapomdp.github.io/POMDPs.jl/latest/api.html#POMDPs.initialstate_distribution)...

**Other methods**
...[check the solver requirements](http://juliapomdp.github.io/POMDPs.jl/latest/requirements.html#requirements-1)...

**Comment by MaximeBouton** [comment]
Which README file are you referring to? 
Thanks for letting us know.

**Comment by BoZenKhaa** [comment]
I think the problem seems to be with the `.html` in many of the github.io links, that doesn't seem to work on github.io. I can try to make a script to fix that all at once in all files if that's truly the issue. I made #15 to fix this in the simulation notebook before noticing this.
